import React from 'react';
import SEO from '../../components/common/SEO';

const sections = [
    {
        id: 'acceptance',
        title: '1. Binding Acceptance and Eligibility',
        content: 'By accessing, browsing, or utilizing the suite of event planning tools provided by ÀRIYÁ, you (the "User") acknowledge that you have read, understood, and unequivocally agree to be bound by these comprehensive Terms of Service. This agreement constitutes a legally binding contract between the User and ÀRIYÁ. If you are entering into this agreement on behalf of a legal entity, such as an event planning agency or corporate enterprise, you represent that you have the requisite legal authority to bind said entity to these terms. Eligibility to use our services is restricted to individuals at least 18 years of age or the age of majority in their jurisdiction. ÀRIYÁ reserves the right to modify these terms at any time, and continued use of the platform following such changes constitutes acceptance of the revised terms.'
    },
    {
        id: 'conduct',
        title: '2. User Account Stewardship and Conduct Standards',
        content: 'Users are granted a non-exclusive, non-transferable, revocable license to access the ÀRIYÁ platform strictly for its intended purpose of event management and vendor collaboration. You are solely responsible for maintaining the strict confidentiality of your account credentials and for all activities that occur under your account. You agree to provide only accurate, current, and complete information regarding your events, budgets, and guest lists. Prohibited conduct includes, but is not limited to: any attempt to circumvent platform security, the use of automated systems (bots/crawlers) to extract proprietary marketplace data, the upload of malicious code, or the harassment of vendors and other users. ÀRIYÁ maintains a zero-tolerance policy for fraudulent event listings or deceptive financial representations, which will result in immediate and permanent account suspension without prior notice.'
    },
    {
        id: 'ai-disclaimer',
        title: '3. Artificial Intelligence Advisory and Limitations',
        content: 'The ÀRIYÁ platform incorporates sophisticated artificial intelligence tools designed to provide predictive planning insights, automated budgeting suggestions, and vendor contract analysis. These AI features are provided "as-is" for informational and efficiency purposes. While we strive for extreme accuracy, ÀRIYÁ does not warrant that the predictions, suggestions, or analyses generated by its AI models are infallible. Users are explicitly advised that all AI-generated content, particularly regarding financial forecasting and legal contract summaries, should be reviewed by qualified human professionals. ÀRIYÁ does not provide legal, financial, or tax advice through its AI tools, and any reliance placed on such automated insights is strictly at the User\'s own risk. We shall not be liable for any planning errors or financial discrepancies resulting from unverified AI recommendations.'
    },
    {
        id: 'marketplace-dynamics',
        title: '4. Vendor Marketplace Intermediation and Liability',
        content: 'ÀRIYÁ operates as an advanced digital intermediary, facilitating the discovery and engagement of third-party event vendors. Users acknowledge that the actual contract for event services (catering, photography, venue rental, etc.) is a direct bilateral agreement between the User and the respective Vendor. ÀRIYÁ is not a party to these service contracts. While we perform baseline verification on vendor participants, we do not guarantee the quality, safety, legality, or punctuality of the services provided by Vendors. Any disputes arising from vendor performance, including service failures or quality complaints, must be resolved directly with the Vendor. Our role is limited to hosting the marketplace environment and providing communication facilitation tools; we do not assume liability for the actions, omissions, or errors of any third-party service provider discovered through our platform.'
    },
    {
        id: 'ip-ownership',
        title: '5. Intellectual Property Rights and Data Licensing',
        content: 'The architectural design, source code, proprietary AI algorithms, brand assets (including the ÀRIYÁ mark), and all original content provided by ÀRIYÁ are the exclusive intellectual property of ÀRIYÁ and its licensors. Users retain full ownership of the specific event data, guest lists, and media files they upload to their accounts. However, by uploading content to the platform, you grant ÀRIYÁ a worldwide, royalty-free, and non-exclusive license to host, store, and process such data solely for the purpose of providing and improving our services. You represent and warrant that you possess all necessary rights to the data you upload and that its use by ÀRIYÁ does not infringe upon the intellectual property rights of any third party. Unauthorized reproduction or redistribution of ÀRIYÁ’s proprietary technology is strictly prohibited and protected under international copyright and patent laws.'
    },
    {
        id: 'liability-limitation',
        title: '6. Comprehensive Limitation of Liability and Indemnification',
        content: 'To the maximum extent permitted by applicable law, ÀRIYÁ and its affiliates, officers, and employees shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, or goodwill, arising from your access to or use of the services. This includes any damages resulting from unauthorized access to your data or the conduct of any third party on the platform. You agree to indemnify and hold ÀRIYÁ harmless from any claims, damages, or costs (including legal fees) arising from your breach of these Terms or your violation of any law or the rights of a third party. Our total aggregate liability for all claims related to the services shall not exceed the amount paid by you to ÀRIYÁ for the use of the services in the six months preceding the event giving rise to the claim.'
    },
];

export default function TermsOfServicePage() {
    return (
        <main className="pt-32 pb-24 bg-white dark:bg-gray-950 min-h-screen">
            <SEO
                title="Terms of Service"
                description="Read the Terms of Service for ÀRIYÁ to understand your rights and obligations."
            />

            <div className="max-w-4xl mx-auto px-8">
                <div className="mb-16">
                    <span className="section-label">Legal</span>
                    <h1 className="text-5xl font-black tracking-tighter mt-4 mb-6">Terms of Service</h1>
                    <p className="text-gray-500 dark:text-gray-400 font-medium">Last updated: February 5, 2026</p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-4 gap-12">
                    <aside className="hidden md:block">
                        <nav className="sticky top-32 space-y-4">
                            {sections.map((section) => (
                                <a
                                    key={section.id}
                                    href={`#${section.id}`}
                                    className="block text-xs font-bold uppercase tracking-widest text-gray-400 hover:text-primary-600 transition-colors"
                                >
                                    {section.title}
                                </a>
                            ))}
                        </nav>
                    </aside>

                    <div className="md:col-span-3 space-y-12">
                        {sections.map((section) => (
                            <section key={section.id} id={section.id} className="scroll-mt-32">
                                <h2 className="text-xl font-black uppercase tracking-widest mb-6 text-gray-900 dark:text-white">
                                    {section.title}
                                </h2>
                                <div className="prose prose-gray dark:prose-invert max-w-none">
                                    <p className="text-gray-600 dark:text-gray-400 leading-relaxed font-medium">
                                        {section.content}
                                    </p>
                                </div>
                            </section>
                        ))}
                    </div>
                </div>
            </div>
        </main>
    );
}
